name: Python CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Change to desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


	- name: Deploy FastAPI app with Gunicorn
	  run: |
	    echo "Starting FastAPI app deployment..."
	    gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 103.73.191.240:8000 main:app
