name: CI/CD for FastAPI

on:
  push:
    branches: [master]  # Define the branch to trigger the workflow
  pull_request:
    branches: [master]  

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5 
      - name: Install dependencies
        run: |
          python -m pip install uvicorn
          # python -m pip install --upgrade pip
          # pip install -r requirements.txt  # Replace with your requirements file
  
      - name: Deploy FastAPI app
        run: python -m uvicorn main:app --host 103.73.191.240 --port 8000  



