name: CI/CD for FastAPI

on:
  push:
    branches: [master]  # Define the branch to trigger the workflow
  pull_request:
    branches: [master]  

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5  # Set the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        run: |
          uvicorn API:app --reload --host 103.73.191.240